version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/oddok-frontend

permissions:
  - object: /home/ubuntu/oddok-frontend
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  ApplicationStart:
    - location: scripts/fe-deploy.sh
      timeout: 300
      runas: ubuntu
